const API_URL_KEY='splitlab_apps_script_url',API_KEY_SESSION='splitlab_api_key',PROJECT_STORAGE_KEY='splitlab_projects_v2';
const CATEGORY_LABELS={melody:'メインメロディー',structure:'構成・展開',motif:'モチーフ／フレーズ',harmony:'コード／ハーモニー',beat:'ビート',bass:'ベース',guitar:'ギター',instrument:'楽器トラック',sound:'サウンドデザイン',sample:'サンプル／ループ',mix:'ミックス',delivery:'編集・納品'};
const projectId=new URLSearchParams(location.search).get('project')||'';
let project=null,analysis=null,saveTimer=null,saveInFlight=false,queuedSaveStatus=null,toastTimer=null;
const $=id=>document.getElementById(id);
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const clamp=(value,min,max,fallback)=>Number.isFinite(Number(value))?Math.max(min,Math.min(max,Number(value))):fallback;
const level=(value,fallback=3)=>Math.round(clamp(value,1,5,fallback));
const adoptionLevel=value=>Math.round(clamp(value,0,5,3));
const confidence=value=>{let n=Number(value);if(!Number.isFinite(n))return .5;if(n>1)n/=100;return Math.max(0,Math.min(1,n));};
const namedPerson=value=>String(value).toLowerCase()==='riku'||value==='B'?'riku':'tada';

function getConnection(){const apiUrl=localStorage.getItem(API_URL_KEY)||'',apiKey=sessionStorage.getItem(API_KEY_SESSION)||'';return apiUrl&&apiKey?{apiUrl,apiKey}:null;}
function localProject(){try{return(JSON.parse(localStorage.getItem(PROJECT_STORAGE_KEY))||[]).find(item=>String(item.id)===String(projectId))||null;}catch{return null;}}
async function postApi(action,payload,timeoutMs=30000){const connection=getConnection();if(!connection)throw new Error('同期設定が必要です。');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const body=new URLSearchParams({action,apiKey:connection.apiKey,payload:JSON.stringify(payload)}),response=await fetch(connection.apiUrl,{method:'POST',body,signal:controller.signal}),result=await response.json();if(!result.ok)throw new Error(result.error||'API処理に失敗しました。');return result;}catch(error){if(error.name==='AbortError')throw new Error('通信がタイムアウトしました。');throw error;}finally{clearTimeout(timer);}}

function renderProject(){
  $('project-title').textContent=project?project.title||'Untitled Track':'案件が見つかりません';
  $('project-meta').textContent=project?`${project.status||'制作中'} / ${project.bpm||'—'} BPM / ${project.logs?.length||0}ログ`:'—';
  $('analyze-btn').disabled=!project||!project.logs?.length||!getConnection();
  const logs=project?.logs||[];$('log-count').textContent=`${logs.length}件`;
  $('log-list').innerHTML=logs.length?logs.map(log=>`<article class="log"><div class="avatar">${escapeHtml(namedPerson(log.person))}</div><div><div class="log-name">${escapeHtml(log.name||'制作作業')} <span class="category-tag">${escapeHtml(CATEGORY_LABELS[log.type]||log.type||'楽器')}</span></div><div class="log-detail">${escapeHtml(log.details||'詳細なし')}<br>影響範囲 ${level(log.scope)} / 制作負荷 ${level(log.effort)}（制作負荷はv3音楽尺度には使用しません）</div></div></article>`).join(''):'<div class="empty">制作ログがありません。メインページで追加してください。</div>';
}

function calculateScores(source){
  const weights=Object.fromEntries((source.categoryWeights||[]).map(item=>[item.category,Math.max(0,Number(item.weight)||0)]));
  const eligible=(source.elements||[]).map(element=>({...element,contributors:(element.contributors||[]).filter(item=>adoptionLevel(item.adoptionScore)>0)})).filter(element=>element.contributors.length);
  const categories=[...new Set(eligible.map(element=>element.category))];let tadaPoints=0,rikuPoints=0;const categoryBreakdown=[];
  categories.forEach(category=>{const elements=eligible.filter(element=>element.category===category),factors=elements.map(element=>.6*level(element.identityScore)/5+.4*level(element.scopeScore)/5),factorTotal=factors.reduce((sum,item)=>sum+item,0)||1;let tada=0,riku=0;
    elements.forEach((element,index)=>{const elementPoints=(weights[category]||0)*factors[index]/factorTotal,contributorScores=element.contributors.map(item=>({person:namedPerson(item.person),score:.4*level(item.roleScore)/5+.35*adoptionLevel(item.adoptionScore)/5+.25*level(item.irreplaceabilityScore)/5})),total=contributorScores.reduce((sum,item)=>sum+item.score,0)||1;contributorScores.forEach(item=>{const points=elementPoints*item.score/total;if(item.person==='riku')riku+=points;else tada+=points;});});
    tadaPoints+=tada;rikuPoints+=riku;categoryBreakdown.push({category,weight:weights[category]||0,tadaPoints:tada,rikuPoints:riku});
  });
  const total=tadaPoints+rikuPoints,tadaPercent=total?tadaPoints/total*100:50,reviewItems=[];
  (source.categoryWeights||[]).forEach(item=>{if(confidence(item.confidence)<.7||!String(item.reason||'').trim())reviewItems.push(`カテゴリ: ${CATEGORY_LABELS[item.category]||item.category}`);});
  (source.elements||[]).forEach(element=>{if(confidence(element.confidence)<.7||!String(element.evidence||'').trim())reviewItems.push(`要素: ${element.name}`);(element.contributors||[]).forEach(item=>{if(confidence(item.confidence)<.7||!String(item.evidence||'').trim())reviewItems.push(`${element.name}: ${namedPerson(item.person)}`);});});
  return{tadaPercent,rikuPercent:100-tadaPercent,categoryBreakdown,reviewItems};
}
function weightTotal(){return(analysis?.categoryWeights||[]).reduce((sum,item)=>sum+Math.max(0,Number(item.weight)||0),0);}
function weightsValid(){return Math.abs(weightTotal()-100)<.051;}
function confidenceBadge(value){const percent=Math.round(confidence(value)*100);return`<span class="confidence ${percent<70?'low':''}">確信度 ${percent}%${percent<70?' · 要確認':''}</span>`;}

function renderAnalysis(){
  const hasAnalysis=analysis&&analysis.metricVersion===3;$('empty-analysis').classList.toggle('hidden',hasAnalysis);$('analysis-content').classList.toggle('hidden',!hasAnalysis);$('confirm-btn').disabled=!hasAnalysis||!weightsValid()||!getConnection();
  if(!hasAnalysis){$('analysis-status').className='status-pill';$('analysis-status').textContent='未分析';return;}
  $('analysis-status').className=`status-pill ${analysis.status==='confirmed'?'confirmed':'draft'}`;$('analysis-status').textContent=analysis.status==='confirmed'?'確認済み':'下書き';$('analysis-summary').textContent=analysis.summary||'';
  $('category-weights').innerHTML=analysis.categoryWeights.map((item,index)=>`<article class="weight-item"><div class="weight-top"><span class="weight-label">${escapeHtml(CATEGORY_LABELS[item.category]||item.category)}</span><input class="number category-weight-input" data-category-index="${index}" type="number" min="0" max="100" step="0.1" value="${Number(item.weight).toFixed(1)}" aria-label="${escapeHtml(CATEGORY_LABELS[item.category]||item.category)}の重要度"></div><div class="reason">${escapeHtml(item.reason||'根拠なし')}</div>${confidenceBadge(item.confidence)}</article>`).join('');
  $('element-list').innerHTML=analysis.elements.map((element,ei)=>`<article class="element"><div class="element-head"><div><h3 class="element-name">${escapeHtml(element.name)}</h3><span class="category-tag">${escapeHtml(CATEGORY_LABELS[element.category]||element.category)}</span></div>${confidenceBadge(element.confidence)}</div><div class="axis-grid"><div class="axis"><label>曲の核への近さ</label><input class="number axis-input" data-element="${ei}" data-field="identityScore" type="number" min="1" max="5" step="1" value="${level(element.identityScore)}"></div><div class="axis"><label>影響範囲</label><input class="number axis-input" data-element="${ei}" data-field="scopeScore" type="number" min="1" max="5" step="1" value="${level(element.scopeScore)}"></div></div><p class="evidence">根拠: ${escapeHtml(element.evidence||'根拠なし')}</p><div class="contributors">${element.contributors.map((item,ci)=>`<div class="contributor"><div class="contributor-top"><div><span class="person ${namedPerson(item.person)}">${namedPerson(item.person)}</span><span class="role"> · ${escapeHtml(item.role||'役割不明')}</span></div>${confidenceBadge(item.confidence)}</div><div class="contributor-grid"><div class="axis"><label>原案・発展の役割</label><input class="number contributor-input" data-element="${ei}" data-contributor="${ci}" data-field="roleScore" type="number" min="1" max="5" step="1" value="${level(item.roleScore)}"></div><div class="axis"><label>最終版への残存</label><input class="number contributor-input" data-element="${ei}" data-contributor="${ci}" data-field="adoptionScore" type="number" min="0" max="5" step="1" value="${adoptionLevel(item.adoptionScore)}"></div><div class="axis"><label>抜いた場合の影響</label><input class="number contributor-input" data-element="${ei}" data-contributor="${ci}" data-field="irreplaceabilityScore" type="number" min="1" max="5" step="1" value="${level(item.irreplaceabilityScore)}"></div></div><p class="evidence" style="padding:10px 0 0">根拠: ${escapeHtml(item.evidence||'根拠なし')}</p></div>`).join('')}</div></article>`).join('');
  updateComputedPanels();
}
function updateComputedPanels(){
  if(!analysis)return;const total=weightTotal();$('weight-total').textContent=`合計 ${total.toFixed(1)}%`;$('weight-total').classList.toggle('invalid',!weightsValid());const result=calculateScores(analysis);analysis.calculation={tadaPercent:result.tadaPercent,rikuPercent:result.rikuPercent,needsReviewCount:result.reviewItems.length,reviewItems:result.reviewItems};
  $('score-text').innerHTML=`tada ${result.tadaPercent.toFixed(1)}% <small>/ riku ${result.rikuPercent.toFixed(1)}%</small>`;$('score-bar-a').style.width=`${result.tadaPercent}%`;$('score-bar-b').style.width=`${result.rikuPercent}%`;$('score-state').textContent=analysis.status==='confirmed'?'確認済み':'暫定値';$('score-state').className=`status-pill ${analysis.status==='confirmed'?'confirmed':'draft'}`;
  $('review-count').textContent=result.reviewItems.length;$('review-text').textContent=result.reviewItems.length?'確信度70%未満、または根拠不足の項目です。確認後も記録は保持されます。':'要確認項目はありません。';$('review-list').classList.toggle('hidden',!result.reviewItems.length);$('review-list').innerHTML=result.reviewItems.slice(0,8).map(item=>`・${escapeHtml(item)}`).join('<br>');
  $('category-breakdown').innerHTML=result.categoryBreakdown.map(item=>{const sum=item.tadaPoints+item.rikuPoints||1,a=item.tadaPoints/sum*100;return`<div class="breakdown-row"><span>${escapeHtml(CATEGORY_LABELS[item.category]||item.category)}</span><div class="mini-bar"><span class="bar-a" style="width:${a}%"></span><span class="bar-b" style="width:${100-a}%"></span></div><span>${a.toFixed(0)} / ${(100-a).toFixed(0)}</span></div>`;}).join('');$('confirm-btn').disabled=!weightsValid()||!getConnection();
}

function markDraftAndScheduleSave(){if(!analysis)return;analysis.status='draft';analysis.confirmedAt='';$('analysis-status').className='status-pill draft';$('analysis-status').textContent='下書き';updateComputedPanels();clearTimeout(saveTimer);if(weightsValid()&&getConnection())saveTimer=setTimeout(()=>saveAnalysis('draft'),700);else $('sync-state').textContent=weightsValid()?'接続後に保存します':'カテゴリ合計を100%にしてください';}
async function saveAnalysis(status){if(!analysis||!weightsValid())return false;if(saveInFlight){queuedSaveStatus=status==='confirmed'?'confirmed':(queuedSaveStatus||status);$('sync-state').textContent=status==='confirmed'?'確認保存を待機中…':'変更の保存を待機中…';return false;}saveInFlight=true;$('sync-state').textContent=status==='confirmed'?'確認済みとして保存中…':'下書きを保存中…';try{const result=await postApi('saveBeta',{projectId,projectTitle:project?.title||'Untitled Track',status,analysis});analysis=result.analysis;$('sync-state').textContent=status==='confirmed'?'確認済み / Sheets同期済み':'下書き / Sheets同期済み';renderAnalysis();return true;}catch(error){$('sync-state').textContent=`保存エラー: ${error.message}`;showToast(`保存エラー: ${error.message}`);return false;}finally{saveInFlight=false;const nextStatus=queuedSaveStatus;queuedSaveStatus=null;if(nextStatus)setTimeout(()=>saveAnalysis(nextStatus),0);}}
async function loadRemote(){if(!projectId){$('sync-state').textContent='URLに案件IDがありません';renderProject();return;}project=localProject();renderProject();if(!getConnection()){$('sync-state').textContent='同期設定が必要です';openConnection();return;}$('sync-state').textContent='案件とベータ分析を取得中…';try{const result=await postApi('loadBeta',{projectId});project=result.project||project;analysis=result.analysis||null;$('sync-state').textContent=analysis?'Sheetsから取得しました':'案件を取得しました';renderProject();renderAnalysis();}catch(error){$('sync-state').textContent=`取得エラー: ${error.message}`;renderProject();renderAnalysis();showToast(`取得エラー: ${error.message}`);}}
async function runAnalysis(){if(!project?.logs?.length)return;$('analyze-btn').disabled=true;$('analyze-btn').textContent='分析中…';$('sync-state').textContent='AIが音楽要素を整理しています…';try{const result=await postApi('analyzeBeta',{project:{title:project.title,status:project.status,client:project.client,bpm:project.bpm,duration:project.duration},logs:project.logs},90000);analysis=result.analysis;renderAnalysis();await saveAnalysis('draft');showToast('ベータ分析を作成しました');}catch(error){$('sync-state').textContent=`分析エラー: ${error.message}`;showToast(`分析エラー: ${error.message}`);}finally{$('analyze-btn').disabled=!project?.logs?.length||!getConnection();$('analyze-btn').textContent='AIで仮採点';}}
function normalizeWeights(){if(!analysis?.categoryWeights?.length)return;let total=weightTotal();if(!total){analysis.categoryWeights.forEach(item=>item.weight=1);total=analysis.categoryWeights.length;}let allocated=0;analysis.categoryWeights.forEach((item,index)=>{item.weight=index===analysis.categoryWeights.length-1?Math.max(0,100-allocated):Math.round(Math.max(0,Number(item.weight)||0)/total*1000)/10;allocated+=item.weight;});renderAnalysis();markDraftAndScheduleSave();}
function openConnection(){$('api-url').value=localStorage.getItem(API_URL_KEY)||'';$('api-key').value='';$('connection-error').classList.add('hidden');$('connection-modal').classList.remove('hidden');}
function closeConnection(){$('connection-modal').classList.add('hidden');}
function showToast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),2600);}
function applyTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('splitlab_theme',theme);$('theme-toggle').textContent=theme==='dark'?'☀️':'🌙';}
$('theme-toggle').textContent=document.documentElement.dataset.theme==='dark'?'☀️':'🌙';
$('theme-toggle').addEventListener('click',()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));

$('analysis-content').addEventListener('input',event=>{if(!analysis)return;const categoryInput=event.target.closest('.category-weight-input');if(categoryInput)analysis.categoryWeights[Number(categoryInput.dataset.categoryIndex)].weight=Math.max(0,Number(categoryInput.value)||0);const axisInput=event.target.closest('.axis-input');if(axisInput)analysis.elements[Number(axisInput.dataset.element)][axisInput.dataset.field]=level(axisInput.value);const contributorInput=event.target.closest('.contributor-input');if(contributorInput){const contributor=analysis.elements[Number(contributorInput.dataset.element)].contributors[Number(contributorInput.dataset.contributor)];contributor[contributorInput.dataset.field]=contributorInput.dataset.field==='adoptionScore'?adoptionLevel(contributorInput.value):level(contributorInput.value);}markDraftAndScheduleSave();});
$('analyze-btn').addEventListener('click',runAnalysis);$('normalize-btn').addEventListener('click',normalizeWeights);$('confirm-btn').addEventListener('click',async()=>{if(!weightsValid())return showToast('カテゴリ重要度の合計を100%にしてください');clearTimeout(saveTimer);const saved=await saveAnalysis('confirmed');if(saved)showToast('確認済みとして保存しました');});$('connection-btn').addEventListener('click',openConnection);$('connection-cancel').addEventListener('click',closeConnection);
$('connection-form').addEventListener('submit',event=>{event.preventDefault();const apiUrl=$('api-url').value.trim(),apiKey=$('api-key').value;if(!/^https:\/\/script\.google\.com\//.test(apiUrl)){$('connection-error').textContent='有効なApps Script Web App URLを入力してください。';$('connection-error').classList.remove('hidden');return;}localStorage.setItem(API_URL_KEY,apiUrl);sessionStorage.setItem(API_KEY_SESSION,apiKey);closeConnection();loadRemote();});$('connection-modal').addEventListener('click',event=>{if(event.target===$('connection-modal'))closeConnection();});
project=localProject();renderProject();renderAnalysis();loadRemote();
